[App]
Name = "wbia_identification_pipeline"
Version = "0.0.3"
Title = "WBIA Identification Pipeline"
Description = "A demonstration of Wild Me's image identification pipeline."
LongDescription = "about.md"
Category = "Data Science"
Keywords = ["wildme", "wildbook", "sage", "wbia", "marked recapture", "conservation", "wave", "wave-apps", "storage"]

[Runtime]
Module = "sage_identification_pipeline.app"
