[App]
Name = "wbia_identification_pipeline"
Version = "0.0.2"
Title = "WBIA Identification Pipeline"
Description = "Demonstration of Wild Me's WBIA Identification Pipeline, built for the H2O.ai cloud app store."
LongDescription = "about.md"
Category = "Data Science"
Keywords = ["wildme", "wildbook", "sage", "wbia", "marked recapture", "conservation", "wave", "wave-apps", "storage"]

[Runtime]
Module = "sage_identification_pipeline.app"
