[App]
Name = "sage_identification_pipeline"
Version = "0.0.1"
Title = "Sage Identification Pipeline"
Description = "A place to save app data and share with other apps."
LongDescription = "about.md"
Category = "Other"
Keywords = ["wildme", "wildbook", "sage", "marked recapture", "conservation", "wave", "wave-apps", "storage"]

[Runtime]
Module = "sage_identification_pipeline.app"
EnableOIDC = true
VolumeSize = "50Gi"
VolumeMount = "/minio"
MemoryLimit = "8Gi"
MemoryReservation = "8Gi"

[[Env]]
Name = "RESTRICT_ACCESS_TO_H2OAI_ONLY"
Value = "false"
